import { Currency } from './types'

export const CURRENCIES: Currency[] = [
  // Base
  { code: 'USD', title: 'US Dollar', symbol: '$', decimals: 2 },

  // Frankfurter (ECB) fiat
  { code: 'EUR', title: 'Euro', symbol: '€', decimals: 2 },
  { code: 'GBP', title: 'British Pound', symbol: '£', decimals: 2 },
  { code: 'JPY', title: 'Japanese Yen', symbol: '¥', decimals: 0 },
  { code: 'CNY', title: 'Chinese Yuan', symbol: '¥', decimals: 2 },
  { code: 'KRW', title: 'South Korean Won', symbol: '₩', decimals: 0 },
  { code: 'CAD', title: 'Canadian Dollar', symbol: 'CA$', decimals: 2 },
  { code: 'AUD', title: 'Australian Dollar', symbol: 'A$', decimals: 2 },
  { code: 'CHF', title: 'Swiss Franc', symbol: 'CHF', decimals: 2 },
  { code: 'HKD', title: 'Hong Kong Dollar', symbol: 'HK$', decimals: 2 },
  { code: 'SGD', title: 'Singapore Dollar', symbol: 'S$', decimals: 2 },
  { code: 'SEK', title: 'Swedish Krona', symbol: 'kr', decimals: 2 },
  { code: 'NOK', title: 'Norwegian Krone', symbol: 'kr', decimals: 2 },
  { code: 'DKK', title: 'Danish Krone', symbol: 'kr', decimals: 2 },
  { code: 'NZD', title: 'New Zealand Dollar', symbol: 'NZ$', decimals: 2 },
  { code: 'MXN', title: 'Mexican Peso', symbol: 'MX$', decimals: 2 },
  { code: 'BRL', title: 'Brazilian Real', symbol: 'R$', decimals: 2 },
  { code: 'PLN', title: 'Polish Zloty', symbol: 'zł', decimals: 2 },
  { code: 'THB', title: 'Thai Baht', symbol: '฿', decimals: 2 },
  { code: 'INR', title: 'Indian Rupee', symbol: '₹', decimals: 2 },
  { code: 'IDR', title: 'Indonesian Rupiah', symbol: 'Rp', decimals: 0 },
  { code: 'HUF', title: 'Hungarian Forint', symbol: 'Ft', decimals: 0 },
  { code: 'CZK', title: 'Czech Koruna', symbol: 'Kč', decimals: 2 },
  { code: 'ILS', title: 'Israeli Shekel', symbol: '₪', decimals: 2 },
  { code: 'PHP', title: 'Philippine Peso', symbol: '₱', decimals: 2 },
  { code: 'MYR', title: 'Malaysian Ringgit', symbol: 'RM', decimals: 2 },
  { code: 'RON', title: 'Romanian Leu', symbol: 'lei', decimals: 2 },
  { code: 'BGN', title: 'Bulgarian Lev', symbol: 'лв', decimals: 2 },
  { code: 'ISK', title: 'Icelandic Krona', symbol: 'kr', decimals: 0 },
  { code: 'TRY', title: 'Turkish Lira', symbol: '₺', decimals: 2 },
  { code: 'ZAR', title: 'South African Rand', symbol: 'R', decimals: 2 },

  // ExchangeRate API fiat (not in Frankfurter)
  { code: 'RUB', title: 'Russian Ruble', symbol: '₽', decimals: 2 },
  { code: 'UAH', title: 'Ukrainian Hryvnia', symbol: '₴', decimals: 2 },
  { code: 'VND', title: 'Vietnamese Dong', symbol: '₫', decimals: 0 },
  { code: 'AED', title: 'UAE Dirham', symbol: 'د.إ', decimals: 2 },
  { code: 'ARS', title: 'Argentine Peso', symbol: 'AR$', decimals: 2 },
  { code: 'BDT', title: 'Bangladeshi Taka', symbol: '৳', decimals: 2 },
  { code: 'CLP', title: 'Chilean Peso', symbol: 'CL$', decimals: 0 },
  { code: 'COP', title: 'Colombian Peso', symbol: 'CO$', decimals: 0 },
  { code: 'EGP', title: 'Egyptian Pound', symbol: 'E£', decimals: 2 },
  { code: 'GEL', title: 'Georgian Lari', symbol: '₾', decimals: 2 },
  { code: 'KZT', title: 'Kazakhstani Tenge', symbol: '₸', decimals: 2 },
  { code: 'NGN', title: 'Nigerian Naira', symbol: '₦', decimals: 2 },
  { code: 'PEN', title: 'Peruvian Sol', symbol: 'S/', decimals: 2 },
  { code: 'PKR', title: 'Pakistani Rupee', symbol: '₨', decimals: 2 },
  { code: 'SAR', title: 'Saudi Riyal', symbol: 'ر.س', decimals: 2 },
  { code: 'TWD', title: 'New Taiwan Dollar', symbol: 'NT$', decimals: 2 },
  { code: 'UZS', title: 'Uzbekistani Som', symbol: 'сўм', decimals: 0 },

  // Crypto (CoinGecko)
  { code: 'BTC', title: 'Bitcoin', symbol: '₿', decimals: 8 },
  { code: 'ETH', title: 'Ethereum', symbol: 'Ξ', decimals: 8 },
  { code: 'TON', title: 'Toncoin', symbol: 'TON', decimals: 9 },
  { code: 'BNB', title: 'BNB', symbol: 'BNB', decimals: 8 },
  { code: 'XRP', title: 'XRP', symbol: 'XRP', decimals: 6 },
  { code: 'SOL', title: 'Solana', symbol: 'SOL', decimals: 9 },
  { code: 'ADA', title: 'Cardano', symbol: 'ADA', decimals: 6 },
  { code: 'DOGE', title: 'Dogecoin', symbol: 'DOGE', decimals: 8 },
  { code: 'DOT', title: 'Polkadot', symbol: 'DOT', decimals: 10 },
  { code: 'AVAX', title: 'Avalanche', symbol: 'AVAX', decimals: 9 },
  { code: 'LINK', title: 'Chainlink', symbol: 'LINK', decimals: 8 },
  { code: 'LTC', title: 'Litecoin', symbol: 'LTC', decimals: 8 },
  { code: 'TRX', title: 'TRON', symbol: 'TRX', decimals: 6 },
  { code: 'POL', title: 'Polygon', symbol: 'POL', decimals: 8 },
  { code: 'UNI', title: 'Uniswap', symbol: 'UNI', decimals: 8 },
  { code: 'XLM', title: 'Stellar', symbol: 'XLM', decimals: 7 },
]
